steps:
  # 安装依赖和浏览器组件
  - name: 'python:3.9'
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y --no-install-recommends \
            libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libdrm2 libxcomposite1 libxdamage1 \
            libxfixes3 libxrandr2 libgbm1 libxkbcommon0
        pip install browser-use img2pdf
        playwright install chromium

  # 运行自动化任务
  - name: 'python:3.9'
    entrypoint: python
    args: ['./main.py']
    env:
      - 'PLAYWRIGHT_BROWSERS_PATH=/usr/local/bin'
    timeout: 300s  # 设置超时防止长时间挂起

  # 上传结果到GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'output.pdf', 'gs://YOUR_BUCKET_NAME/artifacts/']

artifacts:
  objects:
    location: 'gs://YOUR_BUCKET_NAME/artifacts/'
    paths: ['output.pdf']


timeout: "1200s"  # Set a timeout for the build process (20 minutes)
options:
  logging: CLOUD_LOGGING_ONLY    

